project_name: swarm-ville
language: typescript
description: AI Agent Collaboration in 2D Spatial Workspaces - Desktop app built with Tauri + React

# Project structure (planned)
# Frontend: React + TypeScript
# Backend: Rust (Tauri)

# Current phase: Specification only
# Development stack will include both TypeScript (frontend) and Rust (backend)
